<?php

namespace frontend\controllers;

use common\models\SubCategories;
use common\models\SubSubCategories;
use Yii;
use yii\web\Controller;
use \yii\web\Response;

/**
 * Site controller
 */
class AjaxController extends Controller
{

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionGetSubCategories()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            if (!empty($post['id'])) {
                return SubCategories::GetCategoriesByCatId($post['id']);
            }
        }
        return null;
    }

    public function actionGetSubSubCategories()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            $post = Yii::$app->request->post();
            if (!empty($post['id'])) {
                return SubSubCategories::GetCategoriesByCatId($post['id']);
            }
        }
        return null;
    }
}
